backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Contact"
        name: "contact"
        file: "_data/contact.json"
        fields:
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Hours", name: "hours", widget: "string"}