backend:
  name: github
  repo: CamSafeSydney/camsafesydney-website
  branch: main
  base_url: https://api.netlify.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Contact Information"
        name: "contact"
        file: "_data/contact.json"
        fields:
          - {label: "Phone Number", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Business Hours", name: "hours", widget: "string"}

      - label: "Services"
        name: "services"
        file: "_data/services.json"
        fields:
          - label: "Service List"
            name: "services"
            widget: "list"
            fields:
              - {label: "Service Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Price Range", name: "price", widget: "string"}

      - label: "Testimonials"
        name: "testimonials"
        file: "_data/testimonials.json"
        fields:
          - label: "Client Reviews"
            name: "reviews"
            widget: "list"
            fields:
              - {label: "Client Name", name: "name", widget: "string"}
              - {label: "Business Type", name: "type", widget: "string"}
              - {label: "Review Text", name: "text", widget: "text"}
              - {label: "Rating", name: "rating", widget: "number", min: 1, max: 5}